# Generated by Django 3.2.12 on 2023-07-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.exam')),
                ('exam_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payroll.type')),
            ],
        ),
    ]
