# Generated by Django 3.2.12 on 2023-07-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20230717_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_name',
            new_name='exam_type',
        ),
    ]
